import Head from 'next/head'
//import { Inter } from 'next/font/google'

import { useState, useEffect, ChangeEvent } from 'react';

export default function Mint() {

  const [quantity, setQuantity] = useState<number>(1);
  const [wallet, setWallet] = useState<string>("");
  const [message, setMessage] = useState<string>("");

  useEffect(() => {
    const wallet = localStorage.getItem("wallet");
    if (wallet)
      setWallet(wallet);
  },[])

  function onQuantityChange(evt: ChangeEvent<HTMLInputElement>) {
    setQuantity(parseInt(evt.target.value));
  }

  function btnMintClick() {
    setMessage("Minting");
    alert("Mint!!!");
  }
  
  function btnLoginClick() {
    setMessage("Logging in");
    setWallet("0x957339c0b3F129B5AF1DF15A2cAb1301f6799f93");
    localStorage.setItem("wallet","0x957339c0b3F129B5AF1DF15A2cAb1301f6799f93");
    alert("Login!!!");
  }
  
  function btnLogoutClick() {
    setMessage("Logging out");
    localStorage.removeItem("wallet");
    setWallet("");
    alert("Logout!!!");
    setMessage("");
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Mint Page</h1>
        <hr />
        <br />
        {
            wallet
            ? (
              <p>
                <label htmlFor="">
                  Quantity:
                  <input type="number" id="quantity" value={quantity} onChange={onQuantityChange} />
                </label>
                <button id='btnMint' onClick={btnMintClick}>Mint</button>
              </p>
            )
            : <></>
        }
        <p>
          {
            wallet
            ? (
              <>
                <br />
                <a href={`${process.env.OPENSEA_URL}/${wallet}`} target='_blank'>
                  {wallet}
                </a>
                <br />
                <br />
                <button id='btnLogout' onClick={btnLogoutClick}>Logout</button>
              </>
            )
            : (
              <>
                <br />
                <button id='btnLogin' onClick={btnLoginClick} >Login</button>
              </>
            )
          }
        </p>
        <br />
        <p>
          {message}
        </p>
      </main>
    </>
  )
}
